apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
    run: mywp1
  name: mywp1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: mywp1
  type: NodePort
status:
  loadBalancer: {}
