apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mywp1
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.wordpress }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/managed-by: Helm
    run: mywp1
  type: NodePort
status:
  loadBalancer: {}
